In [ ]:
import numpy as np
import pandas as pd
from pandera.errors import SchemaError
from pandera.pandas import Check, Column, DataFrameSchema

tickets = {
    "clarity": ["I1", "SI2", "SI1", "VS2", "VS1", "VVS2", "VVS1", "IF"],
    "color": ["D", "E", "F", "G", "H", "I", "J"],
    "cut": ["Fair", "Good", "Very Good", "Premium", "Ideal"],
}

# data directory path
diamantes_df = pd.read_parquet("data/04_feature/diamantes_clean.parquet")
diamantes_df.head()

   carat      cut color clarity      depth  table  price     x     y     z
0   1.01  Premium     F      I1  61.799999   60.0   2781  6.39  6.36  3.94
1   1.05     Fair     J     SI2  65.800003   59.0   2789  6.41  6.27  4.18
2   1.04  Premium     G      I1  62.200001   58.0   2801  6.46  6.41  4.00
3   1.00  Premium     J     SI2  62.299999   58.0   2801  6.45  6.34  3.98
4   1.00     Fair     G      I1  66.400002   59.0   2808  6.16  6.09  4.07

In [16]:
schema = DataFrameSchema(
    columns={
        "carat": Column(np.float32, checks=Check.gt(0)),
        "cut": Column(str, checks=Check.isin(tickets["cut"])),
        "color": Column(str, checks=Check.isin(tickets["color"])),
        "clarity": Column(str, checks=Check.isin(tickets["clarity"])),
        "depth": Column(np.float32, checks=Check.gt(0)),
        "table": Column(np.float32, checks=Check.gt(0)),
        "price": Column(np.int64, checks=Check.gt(0)),
        "x": Column(np.float32, checks=Check.gt(0)),
        "y": Column(np.float32, checks=Check.gt(0)),
        "z": Column(np.float32, checks=Check.gt(0)),
    }
)

In [17]:
try:
    validated_df = schema.validate(diamantes_df, lazy=True)
    print("DataFrame validado exitosamente:")
    print(validated_df)
except SchemaError as err:
    print("Errores de validación encontrados:")
    print(err.failure_cases)

DataFrame validado exitosamente:
       carat      cut color clarity      depth  table  price     x     y     z
0       1.01  Premium     F      I1  61.799999   60.0   2781  6.39  6.36  3.94
1       1.05     Fair     J     SI2  65.800003   59.0   2789  6.41  6.27  4.18
2       1.04  Premium     G      I1  62.200001   58.0   2801  6.46  6.41  4.00
3       1.00  Premium     J     SI2  62.299999   58.0   2801  6.45  6.34  3.98
4       1.00     Fair     G      I1  66.400002   59.0   2808  6.16  6.09  4.07
...      ...      ...   ...     ...        ...    ...    ...   ...   ...   ...
18972   1.00     Fair     J     VS2  65.699997   59.0   2811  6.14  6.07  4.01
18973   1.02  Premium     G      I1  60.299999   58.0   2815  6.55  6.50  3.94
18974   1.00  Premium     H      I1  61.299999   60.0   2818  6.43  6.39  3.93
18975   1.00     Fair     H     SI2  65.300003   62.0   2818  6.34  6.12  4.08
18976   1.17  Premium     J      I1  60.200001   61.0   2825  6.90  6.83  4.13

[18977 rows x 10 columns]

In [21]:
df_diamantes_ = pd.read_csv("data/01_raw/diamantes.csv")
df_diamantes_.head()

  carat      cut color clarity depth table price     x     y     z
0  0.23    Ideal     E     SI2  61.5  55.0   326  3.95  3.98  2.43
1  0.21  Premium     E     SI1  59.8  61.0   326  3.89  3.84  2.31
2  0.23     Good     E     VS1  56.9  65.0   327  4.05  4.07  2.31
3  0.29  Premium     I     VS2  62.4  58.0   334  4.20  4.23  2.63
4  0.31     Good     J     SI2  63.3  58.0   335  4.34  4.35  2.75

In [23]:
try:
    schema.validate(df_diamantes_, lazy=True)
except SchemaError as err:
    print("Errores de validación encontrados:")
    print(err.failure_cases)

/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/error_formatters.py:265: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  concat_fn(check_failure_cases)

SchemaErrors: {
    "SCHEMA": {
        "SERIES_CONTAINS_NULLS": [
            {
                "schema": null,
                "column": "carat",
                "check": "not_nullable",
                "error": "non-nullable series 'carat' contains null values:116      NaN117      NaN118      NaN119      NaN120      NaN        ... 53766    NaN53767    NaN53936    NaN53955    NaN53984    NaNName: carat, Length: 67, dtype: object"
            },
            {
                "schema": null,
                "column": "cut",
                "check": "not_nullable",
                "error": "non-nullable series 'cut' contains null values:41       NaN42       NaN43       NaN44       NaN45       NaN        ... 53937    NaN53938    NaN53953    NaN53955    NaN53985    NaNName: cut, Length: 149, dtype: object"
            },
            {
                "schema": null,
                "column": "color",
                "check": "not_nullable",
                "error": "non-nullable series 'color' contains null values:41       NaN42       NaN43       NaN44       NaN45       NaN        ... 53956    NaN53957    NaN53985    NaN53986    NaN53987    NaNName: color, Length: 223, dtype: object"
            },
            {
                "schema": null,
                "column": "clarity",
                "check": "not_nullable",
                "error": "non-nullable series 'clarity' contains null values:41       NaN42       NaN43       NaN44       NaN45       NaN        ... 53933    NaN53939    NaN53951    NaN53958    NaN53987    NaNName: clarity, Length: 274, dtype: object"
            },
            {
                "schema": null,
                "column": "depth",
                "check": "not_nullable",
                "error": "non-nullable series 'depth' contains null values:41       NaN42       NaN43       NaN44       NaN45       NaN        ... 53940    NaN53941    NaN53950    NaN53958    NaN53988    NaNName: depth, Length: 305, dtype: object"
            },
            {
                "schema": null,
                "column": "table",
                "check": "not_nullable",
                "error": "non-nullable series 'table' contains null values:41       NaN42       NaN43       NaN44       NaN45       NaN        ... 53942    NaN53949    NaN53950    NaN53960    NaN53989    NaNName: table, Length: 246, dtype: object"
            },
            {
                "schema": null,
                "column": "price",
                "check": "not_nullable",
                "error": "non-nullable series 'price' contains null values:61       NaN62       NaN63       NaN64       NaN65       NaN        ... 53943    NaN53948    NaN53972    NaN53974    NaN53984    NaNName: price, Length: 271, dtype: object"
            },
            {
                "schema": null,
                "column": "x",
                "check": "not_nullable",
                "error": "non-nullable series 'x' contains null values:61      NaN62      NaN63      NaN64      NaN65      NaN         ..53947   NaN53948   NaN53961   NaN53962   NaN53973   NaNName: x, Length: 140, dtype: float64"
            },
            {
                "schema": null,
                "column": "y",
                "check": "not_nullable",
                "error": "non-nullable series 'y' contains null values:61      NaN62      NaN63      NaN64      NaN65      NaN         ..53946   NaN53947   NaN53961   NaN53963   NaN53971   NaNName: y, Length: 145, dtype: float64"
            },
            {
                "schema": null,
                "column": "z",
                "check": "not_nullable",
                "error": "non-nullable series 'z' contains null values:61      NaN62      NaN63      NaN64      NaN65      NaN66      NaN67      NaN308     NaN358     NaN359     NaN453     NaN455     NaN472     NaN494     NaN495     NaN496     NaN497     NaN498     NaN499     NaN500     NaN501     NaN44556   NaN44557   NaN44558   NaN44559   NaN44560   NaN44561   NaN44562   NaN44563   NaN44564   NaN44565   NaN44566   NaN53226   NaN53228   NaN53703   NaN53806   NaN53807   NaN53808   NaN53809   NaN53810   NaN53811   NaN53812   NaN53813   NaN53814   NaN53815   NaN53816   NaN53817   NaN53818   NaN53819   NaN53927   NaN53945   NaN53971   NaNName: z, dtype: float64"
            }
        ],
        "WRONG_DATATYPE": [
            {
                "schema": null,
                "column": "carat",
                "check": "dtype('float32')",
                "error": "expected series 'carat' to have type float32, got object"
            },
            {
                "schema": null,
                "column": "depth",
                "check": "dtype('float32')",
                "error": "expected series 'depth' to have type float32, got object"
            },
            {
                "schema": null,
                "column": "table",
                "check": "dtype('float32')",
                "error": "expected series 'table' to have type float32, got object"
            },
            {
                "schema": null,
                "column": "price",
                "check": "dtype('int64')",
                "error": "expected series 'price' to have type int64, got object"
            },
            {
                "schema": null,
                "column": "x",
                "check": "dtype('float32')",
                "error": "expected series 'x' to have type float32, got float64"
            },
            {
                "schema": null,
                "column": "y",
                "check": "dtype('float32')",
                "error": "expected series 'y' to have type float32, got float64"
            },
            {
                "schema": null,
                "column": "z",
                "check": "dtype('float32')",
                "error": "expected series 'z' to have type float32, got float64"
            }
        ]
    },
    "DATA": {
        "CHECK_ERROR": [
            {
                "schema": null,
                "column": "carat",
                "check": "greater_than(0)",
                "error": "Error while executing check function: TypeError(\"'>' not supported between instances of 'str' and 'int'\")Traceback (most recent call last):  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/components.py\", line 256, in run_checks    self.run_check(  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/base.py\", line 122, in run_check    check_result: CheckResult = check(check_obj, *args)                                ^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/checks.py\", line 260, in __call__    return backend(check_obj, column)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 358, in __call__    check_output = self.apply(check_obj)                   ^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 157, in apply    return apply_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 165, in apply_field    return self.check_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/function_dispatch.py\", line 26, in __call__    return fn(*args, **kwargs)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/builtin_checks.py\", line 110, in greater_than    return data > min_value           ^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/common.py\", line 76, in new_method    return method(self, other)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py\", line 56, in __gt__    return self._cmp_method(other, operator.gt)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/series.py\", line 6138, in _cmp_method    res_values = ops.comparison_op(lvalues, rvalues, op)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 344, in comparison_op    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 129, in comp_method_OBJECT_ARRAY    result = libops.scalar_compare(x.ravel(), y, op)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"pandas/_libs/ops.pyx\", line 107, in pandas._libs.ops.scalar_compareTypeError: '>' not supported between instances of 'str' and 'int'"
            },
            {
                "schema": null,
                "column": "depth",
                "check": "greater_than(0)",
                "error": "Error while executing check function: TypeError(\"'>' not supported between instances of 'str' and 'int'\")Traceback (most recent call last):  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/components.py\", line 256, in run_checks    self.run_check(  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/base.py\", line 122, in run_check    check_result: CheckResult = check(check_obj, *args)                                ^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/checks.py\", line 260, in __call__    return backend(check_obj, column)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 358, in __call__    check_output = self.apply(check_obj)                   ^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 157, in apply    return apply_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 165, in apply_field    return self.check_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/function_dispatch.py\", line 26, in __call__    return fn(*args, **kwargs)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/builtin_checks.py\", line 110, in greater_than    return data > min_value           ^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/common.py\", line 76, in new_method    return method(self, other)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py\", line 56, in __gt__    return self._cmp_method(other, operator.gt)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/series.py\", line 6138, in _cmp_method    res_values = ops.comparison_op(lvalues, rvalues, op)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 344, in comparison_op    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 129, in comp_method_OBJECT_ARRAY    result = libops.scalar_compare(x.ravel(), y, op)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"pandas/_libs/ops.pyx\", line 107, in pandas._libs.ops.scalar_compareTypeError: '>' not supported between instances of 'str' and 'int'"
            },
            {
                "schema": null,
                "column": "table",
                "check": "greater_than(0)",
                "error": "Error while executing check function: TypeError(\"'>' not supported between instances of 'str' and 'int'\")Traceback (most recent call last):  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/components.py\", line 256, in run_checks    self.run_check(  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/base.py\", line 122, in run_check    check_result: CheckResult = check(check_obj, *args)                                ^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/checks.py\", line 260, in __call__    return backend(check_obj, column)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 358, in __call__    check_output = self.apply(check_obj)                   ^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 157, in apply    return apply_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 165, in apply_field    return self.check_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/function_dispatch.py\", line 26, in __call__    return fn(*args, **kwargs)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/builtin_checks.py\", line 110, in greater_than    return data > min_value           ^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/common.py\", line 76, in new_method    return method(self, other)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py\", line 56, in __gt__    return self._cmp_method(other, operator.gt)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/series.py\", line 6138, in _cmp_method    res_values = ops.comparison_op(lvalues, rvalues, op)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 344, in comparison_op    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 129, in comp_method_OBJECT_ARRAY    result = libops.scalar_compare(x.ravel(), y, op)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"pandas/_libs/ops.pyx\", line 107, in pandas._libs.ops.scalar_compareTypeError: '>' not supported between instances of 'str' and 'int'"
            },
            {
                "schema": null,
                "column": "price",
                "check": "greater_than(0)",
                "error": "Error while executing check function: TypeError(\"'>' not supported between instances of 'str' and 'int'\")Traceback (most recent call last):  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/components.py\", line 256, in run_checks    self.run_check(  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/base.py\", line 122, in run_check    check_result: CheckResult = check(check_obj, *args)                                ^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/checks.py\", line 260, in __call__    return backend(check_obj, column)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 358, in __call__    check_output = self.apply(check_obj)                   ^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 157, in apply    return apply_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/checks.py\", line 165, in apply_field    return self.check_fn(check_obj)           ^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/api/function_dispatch.py\", line 26, in __call__    return fn(*args, **kwargs)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandera/backends/pandas/builtin_checks.py\", line 110, in greater_than    return data > min_value           ^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/common.py\", line 76, in new_method    return method(self, other)           ^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py\", line 56, in __gt__    return self._cmp_method(other, operator.gt)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/series.py\", line 6138, in _cmp_method    res_values = ops.comparison_op(lvalues, rvalues, op)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 344, in comparison_op    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"/workspaces/diamantes/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 129, in comp_method_OBJECT_ARRAY    result = libops.scalar_compare(x.ravel(), y, op)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File \"pandas/_libs/ops.pyx\", line 107, in pandas._libs.ops.scalar_compareTypeError: '>' not supported between instances of 'str' and 'int'"
            }
        ],
        "DATAFRAME_CHECK": [
            {
                "schema": null,
                "column": "cut",
                "check": "isin(['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'])",
                "error": "Column 'cut' failed element-wise validator number 0: isin(['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']) failure cases: 2365, 23567364, 23566, 243564"
            },
            {
                "schema": null,
                "column": "color",
                "check": "isin(['D', 'E', 'F', 'G', 'H', 'I', 'J'])",
                "error": "Column 'color' failed element-wise validator number 0: isin(['D', 'E', 'F', 'G', 'H', 'I', 'J']) failure cases: 32564, wetf, 75, 56"
            },
            {
                "schema": null,
                "column": "clarity",
                "check": "isin(['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF'])",
                "error": "Column 'clarity' failed element-wise validator number 0: isin(['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']) failure cases: 4123465, 654657856, 13243456"
            },
            {
                "schema": null,
                "column": "x",
                "check": "greater_than(0)",
                "error": "Column 'x' failed element-wise validator number 0: greater_than(0) failure cases: 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -623543657.0, 0.0, 0.0"
            },
            {
                "schema": null,
                "column": "y",
                "check": "greater_than(0)",
                "error": "Column 'y' failed element-wise validator number 0: greater_than(0) failure cases: 0.0, 0.0, 0.0, 0.0, 0.0, -765465.0, 0.0, 0.0"
            },
            {
                "schema": null,
                "column": "z",